---
- hosts: all
  user: emil
  become: yes
  tasks:
    - name: add firewall rules by service
      firewalld:
        zone: public
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https
