---
- hosts: all
  user: emil
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: start httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started

    - name: install firewalld
      yum:
        name: firewalld
        state: present

    - name: start firewalld
      ansible.builtin.service:
        name: firewalld
        enabled: yes
        state: started
